name: F. Reppekus
favicon: null
layout_spectrum: 0.5622986
typography_spectrum: 0.87947
title: 'F. Reppekus | Content Hub'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FBFBFB'
    - '#CFCFCF'
    - '#919191'
    - '#5C5C5C'
    - '#161616'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.3754028
purpose: []
